### ISSUE TITLE
Using other HMB_ bag files

### ISSUE THREAD

**Issue by GizemAyas517** [ARiSE-Lab/deepTest#3]
Hello and thank you for the deepTest code,

Unfortunately, I couldn't find the HMB_3 bag file so I wanted to use the other HMB_1, HMB2, files from CH2_002 dataset, however I get "list index out of bounds" errors when I try to do that. How can I use another dataset with deepTest?

Kind regards,

**Comment by yuchi1989** [comment]
Hi I shared the hmb3.bag file here because the original published torrent file(https://github.com/udacity/self-driving-car/blob/master/datasets/CH2/HMB_3.bag.tar.gz.torrent) is not seeding any more. This file may help a lot of people for research purpose. If you use this link you need to adhere to any restriction from the original site(https://github.com/udacity/self-driving-car). Also I don't use it for profit.

https://drive.google.com/file/d/1Cna33hR2aEfS4BGiaUtmyWkiqu9BTce_/view?usp=sharing
